services:
  app:
    build: ./.build/app
    volumes:
      - ./app:/var/www/html
      - ./db-config.php:/var/www/db-config.php
    ports:
      - 80:80
    expose:
     - 9003
    depends_on:
      database:
        condition: service_healthy
  database:
    build: ./.build/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egzamin_zawodowy
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10