services:
  main:
    container_name: main
    build: .
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
  app-mysql:
    container_name: app-mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egzamin_zawodowy
    ports:
      - 3306:3306