services:
  main:
    container_name: main
    build: ./app
    volumes:
      - ./app:/var/www/html
    ports:
      - 80:80
  app-mysql:
    build: ./database/
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: egzamin_zawodowy
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306